In [34]:
import numpy as np

# 例: [[1,2,3],[4,5,6],[7,8,9]] → 5 を 10 にする
a=[[1,2,3],[4,5,6],[7,8,9]]
a[1][1]=10
a=np.array(a)
a

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [5]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7,8,9])
a[a % 2 == 0] *= 2
print(a)


[ 0  1  4  3  8  5 12  7 16  9]


In [6]:
a=[]
for i in range(20):
    a.append(i)
a=np.array(a)

a[a%3==0]*=3
a

array([ 0,  1,  2,  9,  4,  5, 18,  7,  8, 27, 10, 11, 36, 13, 14, 45, 16,
       17, 54, 19])

In [7]:
a=np.array([i for i in range(10)])

a[a%2==1]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
a=np.array([i for i in range(10,51,1)])
a[a>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
a = np.array([1, 2, 3, 4, 5])
a=a*2+10
a

array([12, 14, 16, 18, 20])

In [1]:
import numpy as np
m = np.array([[10, 20],
              [30, 40],
              [50, 60]])
v = np.array([1, 2])

for vec in m:
    vec+=v

m

# → 結果: [[11, 22], [31, 42], [51, 62]]


array([[11, 22],
       [31, 42],
       [51, 62]])

In [2]:
 np.array([1,2,3])+np.array([1,2,3,4]) 

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [7]:
a=np.arange(10,31,1)
print(a[(15<=a) & (a<=25)])

[15 16 17 18 19 20 21 22 23 24 25]


In [8]:
a=np.arange(10,21)
a[a%2==0]+=5
a

array([15, 11, 17, 13, 19, 15, 21, 17, 23, 19, 25])

In [9]:
a=np.arange(10,71,10)
a[a>=30]=100
a

array([ 10,  20, 100, 100, 100, 100, 100])

In [12]:
a=np.array([[1,3],
           [2,4]])

a.T

array([[1, 2],
       [3, 4]])

In [14]:
b=np.array([[5,7],[6,8]])

a.T@b.T

array([[19, 22],
       [43, 50]])

zスコア標準化=(x-平均)/(標準偏差)

In [15]:
a=np.arange(5,26,5)
mean=np.mean(a)
std=np.std(a)
z=(a-mean)/std
z

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [16]:
a = np.array([2, 3])
b = np.array([7, 11])

d=np.linalg.norm(a-b)
d

9.433981132056603

In [19]:
a=np.arange(100,901,200)
a_=(a-np.min(a))/(np.max(a)-np.min(a))
a_

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
import pandas as pd

np.random.seed(0)

data={'身長cm': np.random.normal(loc=170,scale=10,size=10),
      '体重kg': np.random.normal(loc=65,scale=20,size=10),
      '血液': np.random.normal(90,180,size=10)
}

df=pd.DataFrame(data)

df.loc[2, '体重kg']=np.nan
df.loc[5,'血液']=np.nan

print(df)

         身長cm       体重kg          血液
0  187.640523  67.880871 -369.538167
1  174.001572  94.085470  207.651347
2  179.787380        NaN  245.598516
3  192.408932  67.433500  -43.589704
4  188.675580  73.877265  498.555832
5  160.227221  71.673487         NaN
6  179.500884  94.881581   98.236533
7  168.486428  60.896835   56.306907
8  168.967811  71.261354  365.900259
9  174.105985  47.918085  354.484579


In [40]:
df.isnull().sum()

身長cm    0
体重kg    1
血液      1
dtype: int64

In [41]:
df['体重kg']=df['体重kg'].fillna(df['体重kg'].mean())
df['血液']=df['血液'].fillna(df['血液'].mean())
df

身長cm       体重kg          血液
0  187.640523  67.880871 -369.538167
1  174.001572  94.085470  207.651347
2  179.787380  72.212050  245.598516
3  192.408932  67.433500  -43.589704
4  188.675580  73.877265  498.555832
5  160.227221  71.673487  157.067345
6  179.500884  94.881581   98.236533
7  168.486428  60.896835   56.306907
8  168.967811  71.261354  365.900259
9  174.105985  47.918085  354.484579

In [30]:
for col in ['体重kg','血液']:
    df[col]=df[col].fillna(df[col].mean())
df

身長cm       体重kg          血液
0  187.640523  67.880871 -369.538167
1  174.001572  94.085470  207.651347
2  179.787380  72.212050  245.598516
3  192.408932  67.433500  -43.589704
4  188.675580  73.877265  498.555832
5  160.227221  71.673487  157.067345
6  179.500884  94.881581   98.236533
7  168.486428  60.896835   56.306907
8  168.967811  71.261354  365.900259
9  174.105985  47.918085  354.484579

In [42]:
df=df[df['身長cm']<=190]
df

身長cm       体重kg          血液
0  187.640523  67.880871 -369.538167
1  174.001572  94.085470  207.651347
2  179.787380  72.212050  245.598516
4  188.675580  73.877265  498.555832
5  160.227221  71.673487  157.067345
6  179.500884  94.881581   98.236533
7  168.486428  60.896835   56.306907
8  168.967811  71.261354  365.900259
9  174.105985  47.918085  354.484579

In [35]:
df.loc[2]

身長cm    179.787380
体重kg     72.212050
血液      245.598516
Name: 2, dtype: float64

In [46]:
for col in ['身長cm', '体重kg']:
    df[f'{col}_norm']=(df[col]-np.min(df[col]))/(np.max(df[col])-np.min(df[col]))
df

<ipython-input-46-9b7b506b33c6>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'{col}_norm']=(df[col]-np.min(df[col]))/(np.max(df[col])-np.min(df[col]))


身長cm       体重kg          血液  身長cm_norm  体重kg_norm
0  187.640523  67.880871 -369.538167   0.963616   0.425070
1  174.001572  94.085470  207.651347   0.484188   0.983048
2  179.787380  72.212050  245.598516   0.687567   0.517295
4  188.675580  73.877265  498.555832   1.000000   0.552752
5  160.227221  71.673487  157.067345   0.000000   0.505827
6  179.500884  94.881581   98.236533   0.677496   1.000000
7  168.486428  60.896835   56.306907   0.290323   0.276358
8  168.967811  71.261354  365.900259   0.307244   0.497051
9  174.105985  47.918085  354.484579   0.487858   0.000000

In [47]:
filtered_df=df[df['身長cm_norm']>=0.7]
filtered_df

身長cm       体重kg          血液  身長cm_norm  体重kg_norm
0  187.640523  67.880871 -369.538167   0.963616   0.425070
4  188.675580  73.877265  498.555832   1.000000   0.552752